<corteOsGastos>

    FloatLayout:



        #navbar superior

        GridLayout:
            rows: 1
            pos_hint:{"right": 0.96,"top": 0.98}
            size_hint:0.92 , 0.12
            canvas:
                Color
                    rgb: utils.get_color_from_hex("27DF07")
                RoundedRectangle
                    size: self.size
                    pos: self.pos
                    radius: [30]


#apenas placeholder, preciso mudar para canvas rectangle
            ImageButton:
                source: "imgs/placeHolder.png"
                on_release: print("aaa")
            ImageButton:
                source: "imgs/placeHolder.png"
                on_release: print("aaa")
            ImageButton:
                source: "imgs/placeHolder.png"
                on_release: print("aaa")




        #navbar inferior


        ImageButton:
            on_release: print("boximg")
            source: "imgs/placeHolder.png"
            canvas:
                Color
                    rgb: utils.get_color_from_hex("27DF07")
            pos_hint:{"right": 0.96,"top": 0.28}
            size_hint_x: 0.92
            size_hint_y: None
            height: dp(80)

        GridLayout:
            rows: 1
            pos_hint:{"right": 0.96,"top": 0.18}
            size_hint:0.92 , 0.12
            canvas:
                Color
                    rgb: utils.get_color_from_hex("27DF07")
                RoundedRectangle
                    size: self.size
                    pos: self.pos
                    radius: [30]


            ImageButton:
                source: "imgs/placeHolder.png"
                on_release: print("aaa1")
            ImageButton:
                source: "imgs/placeHolder.png"
                on_release: print("aaa2")
            ImageButton:
                source: "imgs/placeHolder.png"
                on_release: print("aaa3")
            ImageButton:
                source: "imgs/placeHolder.png"
                on_release: print("aaa4")
            ImageButton:
                source: "imgs/placeHolder.png"
                on_release: print("aaa5")



