<quizTela>

    FloatLayout:


        #navbar superior (quiz)

        FloatLayout:
            pos_hint:{"right": 1,"top": 1}
            size_hint:1 , 0.085
            canvas:
                Color
                    rgb: utils.get_color_from_hex("27DF07")
                Rectangle
                    size: self.size
                    pos: self.pos


            # Button com background transparente com uma imagem em cima

            Button:
                pos_hint:{"right": 0.15,"top": 0.78}
                size_hint: 0.10 , 0.55

                # print pois não tenho a tela para utilizar meu metodo.

                on_release:
                    print("Voltar")
                    app.mudar_tela("XXX")

                background_color: 0, 0, 0, 0

                Image:
                    size: self.parent.size
                    source:"imgs/btnVoltar1.png"
                    center_x: self.parent.center_x
                    center_y: self.parent.center_y


            # dependendo de como ficar o icone de sequência, simplificar
            # para ImageLabel.

            Image:
                pos_hint:{"right": 0.98,"top": 0.96}
                size_hint: 0.2 , 0.9
                source:"imgs/sequencia.png"







    # elementos principais da tela, precisa realizar alguns ajustes
    # antes de fazer o back-end.



        Label:
            pos_hint:{"right": 0.96,"top": 0.83}
            size_hint: 0.92 , 0.23
            text: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            bold: True
            font_size: 24
            color: 0.024, 0.31, 0.067, 1
            font_size: 20
            halign: "center"
            valign: "center"
            text_size: self.width - 30, self.height - 10
            canvas.before:
                Color:
                    rgb: utils.get_color_from_hex("CBE9C6")
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [40]
            canvas:
                Color:
                    rgb: utils.get_color_from_hex("#114F06")
                Line:
                    rounded_rectangle: (self.x, self.y, self.width, self.height, 40) # traça uma linha com base nos valores dos parâmetros, o ultimo é o raio.
                    width: 1.22




    #haling e valing referem se ao alinhamento horizontal e vertical respectivamente.

    #aqui, o text_size [e usado para delimitar o cmapo ocupado pelo texto e previnir overflow.

        Button:
            pos_hint:{"right": 0.48,"top": 0.38}
            size_hint: 0.46 , 0.15
            text:"Resposta 1"
            font_size: 14
            bold: True
            color: 0, 0, 0, 1 # RGB, sendo o ultimo valor a tansparencia.
            halign: "left"
            valign: "top"
            padding: (15, 15)
            text_size: self.width - 10, self.height - 10
            background_color: 0, 0, 0, 0 # como o ultimo valor é 0 (0%), o elemento fica completamente transparente.
            on_release:print("opção1")
            canvas.before:
                Color:
                    rgba: (0.9, 0.9, 0.9, 1) if self.state == 'normal' else (0.7, 0.7, 0.7, 1)
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [40]
            canvas:
                Color:
                    rgb: utils.get_color_from_hex("#114F06")
                Line:
                    rounded_rectangle: (self.x, self.y, self.width, self.height, 40)
                    width: 1.01
        Button:
            pos_hint:{"right": 0.98,"top": 0.38}
            size_hint: 0.46 , 0.15
            text:"Resposta 2"
            font_size: 14
            bold: True
            color: 0, 0, 0, 1
            halign: "left"
            valign: "top"
            padding: (15, 15)
            text_size: self.width - 10, self.height - 10
            background_color: 0, 0, 0, 0
            on_release:print("opção2")
            canvas.before:
                Color:
                    rgba: (0.9, 0.9, 0.9, 1) if self.state == 'normal' else (0.7, 0.7, 0.7, 1)
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [40]
            canvas:
                Color:
                    rgb: utils.get_color_from_hex("#114F06")
                Line:
                    rounded_rectangle: (self.x, self.y, self.width, self.height, 40)
                    width: 1.01


        Button:
            pos_hint:{"right": 0.48,"top": 0.555}
            size_hint: 0.46 , 0.15
            text:"Resposta 3"
            font_size: 14
            bold: True
            color: 0, 0, 0, 1
            halign: "left"
            valign: "top"
            padding: (15, 15)
            text_size: self.width - 10, self.height - 10
            background_color: 0, 0, 0, 0
            on_release:print("opção3")
            canvas.before:
                Color:
                    rgba: (0.9, 0.9, 0.9, 1) if self.state == 'normal' else (0.7, 0.7, 0.7, 1)
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [40]
            canvas:
                Color:
                    rgb: utils.get_color_from_hex("#114F06")
                Line:
                    rounded_rectangle: (self.x, self.y, self.width, self.height, 40)
                    width: 1.01
        Button:
            pos_hint:{"right": 0.98,"top": 0.555}
            size_hint: 0.46 , 0.15
            text:"Resposta 4"
            font_size: 14
            bold: True
            color: 0, 0, 0, 1
            halign: "left"
            valign: "top"
            padding: (15, 15)
            text_size: self.width - 10, self.height - 10
            background_color: 0, 0, 0, 0
            on_release:print("opção4")
            canvas.before:
                Color:
                    rgba: (0.9, 0.9, 0.9, 1) if self.state == 'normal' else (0.7, 0.7, 0.7, 1)
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [40]
            canvas:
                Color:
                    rgb: utils.get_color_from_hex("#114F06")
                Line:
                    rounded_rectangle: (self.x, self.y, self.width, self.height, 40)
                    width: 1.01















        #navbar inferior

        Image:
            source:"imgs/VNavB1.png"
            pos_hint:{"right": 0.96,"top": 0.14}
            size_hint:0.92 , 0.07





        # Usando grid layout para não precisar declarar a posição e tamanho
        # de cada elemento, além disso ele irá dividir igualmente dentro do
        # layout. caso não funcione, aplicar o mesmo estilo da navbar
        # superior.

        GridLayout:
            rows: 1
            pos_hint:{"right": 0.96,"top": 0.09}
            size_hint:0.92 , 0.07
            canvas:
                Color
                    rgb: utils.get_color_from_hex("27DF07")
                RoundedRectangle
                    size: self.size
                    pos: self.pos
                    radius: [40]







            ImageButton:
                on_release:print("1")
                source:"imgs/icone1.png"
            ImageButton:
                on_release:print("2")
                source:"imgs/icone2.png"
            ImageButton:
                on_release:print("3")
                source:"imgs/icone3.png"
            ImageButton:
                on_release:print("4")
                source:"imgs/icone4.png"
            ImageButton:
                on_release:print("configurações")
                source:"imgs/configuracoes.png"



